### ISSUE TITLE
Downloading in puppeteer

### ISSUE THREAD

**Issue by priyankapuranik** [emadehsan/thal#17]
I have a list of pdf links which I need to download after web scraping using puppeteer! page.pdf() doesnt seem to work!
Any suggestions?

**Comment by sg-s** [comment]
to pile on: once I find a certain image on a page, how do I save that image to disk?

**Comment by emadehsan** [comment]
@priyankapuranik according to [it's documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) currently you can save PDF only in `headless` mode

**Comment by emadehsan** [comment]
@sg-s I think for now you'd have to use some third party library like `request` to download & save files / images to disk. Do tell if you are able to do it by Puppeteer. 

BTW a helpful method to automate process of intercepting certain file types is [`page.setRequestInterceptionEnabled(value)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionenabledvalue)

**Comment by sg-s** [comment]
@emadehsan thanks -- this is a little too deep for me to figure out. i'll wait for someone else to sort this out
