### ISSUE TITLE
How do i clear cache and cookies in headless mode?

### ISSUE THREAD

**Issue by priyankapuranik** [emadehsan/thal#18]

**Comment by emadehsan** [comment]
You can clear cookies with [page.deleteCookie(...cookies)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagedeletecookiecookies) method.

Clearing cache has been discussed [here](https://github.com/GoogleChrome/puppeteer/issues/446) and a way to do this is also mentioned. But still there is no proper method to do this.

**Comment by priyankapuranik** [comment]
Thanks @emadehsan

**Comment by emadehsan** [comment]
@priyankapuranik no problem :)
