### ISSUE TITLE
You don't need to use JSDOM

### ISSUE THREAD

**Issue by paulirish** [emadehsan/thal#2]
I believe two of my colleagues already left a comment on the Medium post with this information..

But you don't need to use JSDOM for text extraction. You can use the `$` method instead. It should make this a lot more simpler.

**Comment by emadehsan** [comment]
Yeah, I have talked to one. I am testing it. I will update the article.

**Comment by emadehsan** [comment]
@paulirish the `$` method returns elementHandle. Currently is there a way of extracting text using without evaluate? I had document object null inside evaluate when I wrote the article. So I used jsdom. 
Now, I have tested and it is working. I am updating the article with `evaluate`.

**Comment by emadehsan** [comment]
Fixed in a2d4333949912d956a430d7b2117f8ff38b643a4
