### ISSUE TITLE
Error executing node.js

### ISSUE THREAD

**Issue by danielwerner-dev** [emadehsan/thal#22]
nodejs index.js

(node:13914) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at <anonymous>:2:43
(node:13914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by danielwerner-dev** [comment]
Any help on that ?

**Comment by emadehsan** [comment]
Hi @danielortiz3 thank you for reporting. I was a bit busy. I am looking at it. It's probably because of Puppeteer update.

**Comment by danielwerner-dev** [comment]
Ok, thanks for ur help!

**Comment by emadehsan** [comment]
The issue was with the selector for selecting number of users. Seems like GitHub had a slight update in there interface for search results.
Anyways, I've pushed the latest changes on GitHub. Pull them and try.
Let me know if still any error pops up.
