### ISSUE TITLE
LENGHT_SELECTOR_CLASS misspelled?

### ISSUE THREAD

**Issue by veb** [emadehsan/thal#3]
Firstly, great work on the tutorial! 

I've noticed you've possibly misspelled your `LENGHT_SELECTOR_CLASS` variable. It should be `LENGTH_SELECTOR_CLASS`. 👍

**Comment by emadehsan** [comment]
Haha, at multiple places. Let me fix

**Comment by emadehsan** [comment]
Thanks. Fixed in https://github.com/emadehsan/thal/commit/539dae128050c0eeacfcaf091608f83d9bad8909
