### ISSUE TITLE
Consider replacing Cred.js with environment variables

### ISSUE THREAD

**Issue by jabranr** [emadehsan/thal#6]
Taking this is not a good practice to hard code credentials, consider using environment variables for such purpose. This will eliminate the requirement of `Cred.js` file completely. 

See my pull request with this update. #5 (cc4a799ac9bb1645e595515f5e61dfba4196abe5)

**Comment by emadehsan** [comment]
Thanks @jabranr for the suggestion. Considering this is getting started guide, I didn't want to complicate things with Environment variables. What do you think? Let's discuss. 

And sorry for late response, I am on vacation and couldn't manage to get proper internet. My connection goes down time and time again.

**Comment by jabranr** [comment]
Fair enough. Though one would argue that at this point anyone using node like this would be quite comfortable with using environment variables. 🙂  No worries for the delay. You must have a life outside GitHub. ;)

**Comment by emadehsan** [comment]
I am looking through you commits. You did a great job! Thanks for the PR.

>  Though one would argue that at this point anyone using node like this would be quite comfortable with using environment variables. 

Good point. But we shouldn't assume that people would know already how to add them. So, if we use environment variables, we'd also have to add to the guide how to add them for all OSes. Because one thing that many of the readers appreciated was the simplicity and clarity of article.

**Comment by jabranr** [comment]
Agreed. Let's keep it as it is for now. I will revert that particular commit and then we can go forward with rest of the updates.

**Comment by emadehsan** [comment]
@jabranr I have merged 2 out of 3 of your commits. Excluded is the one with ENV variables.
