### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by uimator** [emadehsan/thal#9]
when run index.js，i get this error:

```
node index.js
(node:2199) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:2199) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

env:
- node: v8.3.0
- os: 10.12.6

**Comment by emadehsan** [comment]
Thanks for bringing up. This happens when the default time for navigating (30 seconds) exceeds. 
It can be catered by 
1. Surrounding code with a `try catch` block.
Or
2. Increasing the navigation time by some amount by passing `timeout: 90*1000`

**Comment by uimator** [comment]
when i clean the proxy, it's ok.

**Comment by uimator** [comment]
@emadehsan  thanks for reply。

**Comment by emadehsan** [comment]
No problem :+1:
